-- Create notifications table
create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    title text not null,
    message text not null,
    type text not null check (type in ('info', 'warning', 'success', 'error')),
    category text not null,
    unread boolean default true,
    user_id uuid references auth.users(id)
);

-- RLS Policies (Optional, assuming public/admin access for now based on other tables)
alter table public.notifications enable row level security;

create policy "Enable read access for all users"
on public.notifications for select
to public
using (true);

create policy "Enable update for all users"
on public.notifications for update
to public
using (true);

create policy "Enable insert for all users"
on public.notifications for insert
to public
with check (true);

create policy "Enable delete for all users"
on public.notifications for delete
to public
using (true);
